apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: logging
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      if [kubernetes][container][name] == "backend" {
        mutate { add_tag => ["backend"] }
      }
      if [kubernetes][container][name] == "frontend" {
        mutate { add_tag => ["frontend"] }
      }
      if [kubernetes][container][name] == "postgres" {
        mutate { add_tag => ["postgres"] }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.logging.svc.cluster.local:9200"]
        index => "k8s-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
